### ISSUE TITLE
License report for github or local file system dependencies.

### ISSUE THREAD

**Issue by aindlq** [BePo65/license-report#3]
Right now report doesn't work for github dependencies, or local file system dependencies.

Are there any good reasons why package.json file need to be retrieved from npm registry, but not from the local node_modules folder?

**Comment by kessler** [comment]
@aindlq 
Sorry for the delayed reply.

TBH, It's been so long since I wrote this tool I don't remember. What I do remember is that I was struggling with this dilemma. I think maybe it was because I only wanted the tool to require a package.json to operate and nothing else.

I'll go over your PR now.
